name: Arduino Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arduino Lint
        run: |
          mkdir -p ~/bin
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-lint/main/etc/install.sh | BINDIR=~/bin sh

      - name: Add to PATH
        run: echo "$HOME/bin" >> $GITHUB_PATH

      - name: Run Arduino Lint
        run: arduino-lint --compliance strict --library-manager submit